"""Stockpile volume from a point cloud: separate the ground, separate the piles, integrate the height.

The input here is synthetic (generated by make_scene below): piles of known shape on a tilted, slightly curved yard,
with sensor noise and a loader parked between two piles. Real input is the point cloud that photogrammetry
(OpenDroneMap, for example) produces from drone photos. Because the piles are generated, their true volume is known
and the estimate can be checked.

  python stockpile_volume/pipeline.py      # prints true and estimated volume per pile, writes figures
"""
from __future__ import annotations

import json
import os

import numpy as np
from sklearn.cluster import DBSCAN, HDBSCAN

RNG = np.random.default_rng(42)
HERE = os.path.dirname(os.path.abspath(__file__))


# ---- synthetic scene ---------------------------------------------------------------------------------------------

def ground(x, y):
    """A yard that slopes 2% one way, 1% the other, and dishes up about 1.2 m towards the corners."""
    return 0.02 * x + 0.01 * y + 0.0003 * ((x - 50) ** 2 + (y - 40) ** 2)


PILES = [  # (centre x, centre y, radius x, radius y, height)  elliptical cones
    (25, 25, 9, 7, 6.0),
    (55, 30, 11, 8, 7.5),
    (78, 55, 7, 7, 5.0),
    (35, 62, 10, 6, 4.5),
]


def pile_height(x, y, p):
    cx, cy, rx, ry, h = p
    r = np.sqrt(((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2)
    return np.clip(h * (1 - r), 0, None)


def true_volume(p):
    _, _, rx, ry, h = p
    return np.pi * rx * ry * h / 3  # volume of an elliptical cone


def make_scene(density: float = 6.0):
    """Points per square metre ~ density. Returns an (n, 3) array."""
    n = int(100 * 80 * density)
    x, y = RNG.uniform(0, 100, n), RNG.uniform(0, 80, n)
    z = ground(x, y) + sum(pile_height(x, y, p) for p in PILES)
    z += RNG.normal(0, 0.05, n)  # 5 cm photogrammetry noise
    pts = [np.column_stack([x, y, z])]
    # a loader parked between the first two piles: a 3 x 2 x 2.5 m box that touches both footprints
    lx, ly = RNG.uniform(38, 41, 400), RNG.uniform(26, 28, 400)
    pts.append(np.column_stack([lx, ly, ground(lx, ly) + RNG.uniform(0, 2.5, 400)]))
    return np.vstack(pts)


# ---- pipeline ----------------------------------------------------------------------------------------------------

def fit_ground_ransac(pts, iterations=400, tolerance=0.15):
    """RANSAC: the plane with most inliers is the yard. Then a quadratic surface is refit on those inliers,
    because real yards are not flat and a plane leaves a residual that reads as volume."""
    best, best_inliers = None, None
    for _ in range(iterations):
        sample = pts[RNG.choice(len(pts), 3, replace=False)]
        normal = np.cross(sample[1] - sample[0], sample[2] - sample[0])
        if np.linalg.norm(normal) < 1e-9:
            continue
        normal /= np.linalg.norm(normal)
        distance = np.abs((pts - sample[0]) @ normal)
        inliers = distance < tolerance
        if best_inliers is None or inliers.sum() > best_inliers.sum():
            best, best_inliers = (normal, sample[0]), inliers
    g = pts[best_inliers]
    design = lambda p: np.column_stack([np.ones(len(p)), p[:, 0], p[:, 1], p[:, 0] ** 2, p[:, 1] ** 2, p[:, 0] * p[:, 1]])
    coef, *_ = np.linalg.lstsq(design(g), g[:, 2], rcond=None)
    return lambda p: design(p) @ coef


def above_ground(pts, surface, threshold=0.3):
    height = pts[:, 2] - surface(pts)
    keep = height > threshold
    return pts[keep], height[keep]


def remove_thin_objects(pts, height, cell=1.0, min_points=6):
    """Machines and poles are tall and narrow: drop grid cells where few points stand much higher than their
    neighbours' typical height. A crude stand-in for the noise and machine removal step."""
    gx, gy = (pts[:, 0] // cell).astype(int), (pts[:, 1] // cell).astype(int)
    keys = gx * 10_000 + gy
    uniq, inverse, counts = np.unique(keys, return_inverse=True, return_counts=True)
    spread = np.zeros(len(uniq))
    np.maximum.at(spread, inverse, height)
    lo = np.full(len(uniq), np.inf)
    np.minimum.at(lo, inverse, height)
    vertical = (spread - lo)[inverse] > 1.5  # a cell whose points span more than 1.5 m vertically is not a slope
    sparse = counts[inverse] < min_points
    keep = ~(vertical & sparse)
    return pts[keep], height[keep]


def cluster(pts, method="hdbscan"):
    xy = pts[:, :2]
    if method == "dbscan":
        return DBSCAN(eps=0.9, min_samples=25).fit_predict(xy)
    return HDBSCAN(min_cluster_size=300, min_samples=25).fit_predict(xy)


def volume(pts, height, cell=1.0):
    """Integrate height over a grid: mean height per cell times cell area."""
    gx, gy = (pts[:, 0] // cell).astype(int), (pts[:, 1] // cell).astype(int)
    keys = gx * 10_000 + gy
    uniq, inverse = np.unique(keys, return_inverse=True)
    sums = np.bincount(inverse, weights=height)
    counts = np.bincount(inverse)
    return float((sums / counts).sum() * cell * cell)


def run(method="hdbscan", plane_only=False):
    pts = make_scene()
    surface = fit_ground_ransac(pts)
    if plane_only:
        # Same RANSAC plane, without the quadratic refit: shows what the curvature of a real yard costs.
        g = pts[np.abs(pts[:, 2] - surface(pts)) < 0.15]
        coef, *_ = np.linalg.lstsq(np.column_stack([np.ones(len(g)), g[:, 0], g[:, 1]]), g[:, 2], rcond=None)
        surface = lambda p: np.column_stack([np.ones(len(p)), p[:, 0], p[:, 1]]) @ coef
    piles, height = above_ground(pts, surface)
    piles, height = remove_thin_objects(piles, height)
    labels = cluster(piles, method)
    found = []
    for label in sorted(set(labels) - {-1}):
        m = labels == label
        c = piles[m][:, :2].mean(axis=0)
        found.append({"label": int(label), "centre": [round(float(c[0]), 1), round(float(c[1]), 1)],
                      "points": int(m.sum()), "volume_m3": round(volume(piles[m], height[m]), 1)})
    truth = [{"centre": [p[0], p[1]], "volume_m3": round(true_volume(p), 1)} for p in PILES]
    for t in truth:  # match each true pile to the nearest found cluster
        near = min(found, key=lambda f: np.hypot(f["centre"][0] - t["centre"][0], f["centre"][1] - t["centre"][1]), default=None)
        t["estimated_m3"] = near["volume_m3"] if near else None
        t["error_pct"] = round(100 * (near["volume_m3"] - t["volume_m3"]) / t["volume_m3"], 1) if near else None
    return {"method": method, "plane_only": plane_only, "clusters_found": len(found), "piles": truth}, pts, piles, labels


if __name__ == "__main__":
    results = []
    for method, plane in (("hdbscan", False), ("dbscan", False), ("hdbscan", True)):
        r, *_ = run(method, plane)
        results.append(r)
        print(json.dumps(r))
    json.dump(results, open(os.path.join(HERE, "results.json"), "w"), indent=1)
